## **`Working with APIs`**

In [1]:
import requests

In [2]:
URL = "https://potterapi-fedeperin.vercel.app/en/spells"

In [3]:
res = requests.get(URL)

In [4]:
res

In [5]:
data = res.json()

In [6]:
import pandas as pd

In [7]:
df = pd.json_normalize(data[:])

In [8]:
df

,spell,use,index
0,Accio,Summoning charm,0
1,Glisseo,Turns a staircase into a slide,1
2,Impervius,"Protects caster from a variety of substances, ...",2
3,Wingardium Leviosa/Locomotor,Levitates objects,3
4,Scourgify,Cleans things,4
...,...,...,...
67,Fiendfyre Curse,Makes cursed fire,67
68,Tarantallegra,Forces target to dance,68
69,Morsmordre,Conjures the Dark Mark,69
70,Sectumsempra,Causes severe lacerations,70
71,Crucio,Causes immense pain,71

In [9]:
df[0: 11]

,spell,use,index
0,Accio,Summoning charm,0
1,Glisseo,Turns a staircase into a slide,1
2,Impervius,"Protects caster from a variety of substances, ...",2
3,Wingardium Leviosa/Locomotor,Levitates objects,3
4,Scourgify,Cleans things,4
5,Portus,Creates a portkey,5
6,Orchideous,Grows flowers from end of wand,6
7,Lumos,Makes wand emit light,7
8,Reparo,Repairs broken objects,8
9,Reducio,Shrinks objects,9
10,Pack,Packs trunks and luggage,10

In [10]:
df.head()

,spell,use,index
0,Accio,Summoning charm,0
1,Glisseo,Turns a staircase into a slide,1
2,Impervius,"Protects caster from a variety of substances, ...",2
3,Wingardium Leviosa/Locomotor,Levitates objects,3
4,Scourgify,Cleans things,4

In [11]:
df.tail()

              spell                        use  index
67  Fiendfyre Curse          Makes cursed fire     67
68    Tarantallegra     Forces target to dance     68
69       Morsmordre     Conjures the Dark Mark     69
70     Sectumsempra  Causes severe lacerations     70
71           Crucio        Causes immense pain     71