## **`Merging, Joining & Concatenation in Pandas`**

Imagine we work in a company.

we have:
- File 1 → Customer information
- File 2 → Orders information
- File 3 → Payments information

They are stored separately.

But for analysis, we must combine them.

That combining process = Merge / Join / Concatenation

---

In [1]:
import pandas as pd

### **1️⃣ MERGE**

**Merge is used for SQL-like joins and combines two DataFrames based on common columns (keys).**

It supports: 

- Inner join - Only keep common values of both df
- Outer join - Keep all values of both df and replace missing with NaN
- Left join - Keep all values of left df and replace missing with NaN
- Right join - Keep all values of right df and replace missing with NaN

In [2]:
customer_table = pd.DataFrame({
    "customer_id" : [1, 2], 
    "Name" : ["Ali", "Sara"]
})

orders_table = pd.DataFrame({
    "customer_id" : [1, 2, 3],
    "Order" : ["Laptop", "Phone", "PC"]
})

In [3]:
customer_table

   customer_id  Name
0            1   Ali
1            2  Sara

In [4]:
orders_table

   customer_id   Order
0            1  Laptop
1            2   Phone
2            3      PC

In [5]:
pd.merge(customer_table, orders_table, on="customer_id")

   customer_id  Name   Order
0            1   Ali  Laptop
1            2  Sara   Phone

In [6]:
pd.merge(customer_table, orders_table, on="customer_id", how="inner")

   customer_id  Name   Order
0            1   Ali  Laptop
1            2  Sara   Phone

In [7]:
pd.merge(customer_table, orders_table, on="customer_id", how="outer")

   customer_id  Name   Order
0            1   Ali  Laptop
1            2  Sara   Phone
2            3   NaN      PC

In [8]:
pd.merge(customer_table, orders_table, on="customer_id", how="left")

   customer_id  Name   Order
0            1   Ali  Laptop
1            2  Sara   Phone

In [9]:
pd.merge(customer_table, orders_table, on="customer_id", how="right")

   customer_id  Name   Order
0            1   Ali  Laptop
1            2  Sara   Phone
2            3   NaN      PC

---

### **2️⃣ JOIN (Index-Based Merge)**

**It is used to combine two DataFrames based on index by default & can also join on a key column.**

**SHORTCUT MERGE**

When to Use Join? 

- When both DataFrames already share the same index.
- When index is meaningful (like date index)

Important : `merge() is more flexible`  &  `join() is simpler but less powerful`

In [17]:
dff1 = pd.DataFrame({
    "Name" : ["Ali", "Sara", "Zoya"],
}, index=[1, 2, 3])

dff2 = pd.DataFrame({
    "Marks" : [85, 90, 78],
}, index=[1, 2, 3])

In [18]:
dff1

   Name
1   Ali
2  Sara
3  Zoya

In [19]:
dff2

   Marks
1     85
2     90
3     78

In [20]:
dff1.join(dff2)

   Name  Marks
1   Ali     85
2  Sara     90
3  Zoya     78

---

### **3️⃣ Concatenation (Stacking Data)**

**Stacking DataFrames on top of each other (rows) or side by side (columns)**

In [11]:
df1 = pd.DataFrame({
    "id" : [1, 2, 3], 
    "name" : ["Ali", "Sara", "Zoya"]
})

df2 = pd.DataFrame({
    "id" : [4, 5, 6], 
    "name" : ["Alia", "Hamza", "Nouman"]
})

In [12]:
df1

   id  name
0   1   Ali
1   2  Sara
2   3  Zoya

In [13]:
df2

   id    name
0   4    Alia
1   5   Hamza
2   6  Nouman

- **Vertical Concatenation (default)**

Used when:

   Same columns

   More rows

In [ ]:
pd.concat([df1, df2]) # labels are preserved

   id    name
0   1     Ali
1   2    Sara
2   3    Zoya
0   4    Alia
1   5   Hamza
2   6  Nouman

In [15]:
pd.concat([df1, df2], ignore_index=True)

   id    name
0   1     Ali
1   2    Sara
2   3    Zoya
3   4    Alia
4   5   Hamza
5   6  Nouman

- **Horizontal Concatenation**

Used when:

Same number of rows

Different columns

In [16]:
pd.concat([df1, df2], axis=1)

   id  name  id    name
0   1   Ali   4    Alia
1   2  Sara   5   Hamza
2   3  Zoya   6  Nouman