## **`Pandas`**  - **data analysis and manipulation tool**

- **Pandas** is one of the most widely used Python libraries for **data analysis and manipulation**. 

- It is open-source and **built on the top of NumPy**.
- It adds high-level data structures and tools 
that make it easier to work with **tabular**, **labeled**, or **heterogeneous datasets**. 

---

In [1]:
import pandas as pd

#### **Why we need `Pandas` if we already have `NumPy`?**

We already knows NumPy arrays are:
- Fast
- Memory Efficient
- Math Focused

But real-world data is messy. It has:
- Column names
- Missing Values
- Mixed Data types (numbers + text) 
- Data, categories, labels

**NumPy struggles here**

**Pandas was born for this**

---

#### **Where is `Pandas` used?**
- Data Analysis
- Data cleaning
- Machine Learning pre-processing
- Exploratory Data Analysis (EDA) 
- Kaggle competitions 
- Industry datasets (CSV, Excel, SQL)

---

**Pandas has 2 main Data structures:**

**`Pandas`**

├── **`Series`**      **→** ***`1D labeled data (like a column)`***

└── **`DataFrame`**   **→** **`2D table (rows + columns)`**

---

### **``1️⃣ Pandas Series``**

A `Series` is a `one-dimensional labeled array` (like a column in a spreadsheet).

It can hold data of any type: integers, floats, strings, Python objects. 

It has two main components: 

1. **Values** - the actual data 

2. **Index** - labels for each value 

`Series` Properties:

- Homogenous - store one type of data

- Vectorized Operations

- Handle Missing values with NaN

- Mutable Values, immutable size (can't add or delete if we do new series is created)

In [2]:
# Vectorized Operations
s1 = pd.Series([1, 2, 3, 4, 5]) 
s2 = pd.Series([10, 20, 30, 40, 50]) 

print(s1 + s2)

0    11
1    22
2    33
3    44
4    55
dtype: int64

In [3]:
# Mutable values 
s1[0] = 99

# immutable size
changed_s1 = s1.drop(0) 

print(s1) 
print(changed_s1)

0    99
1     2
2     3
3     4
4     5
dtype: int64
1    2
2    3
3    4
4    5
dtype: int64

- **In `Python lists and NumPy arrays`, `indexing` is `position-based and fixed`.**

- **In `Pandas Series`, the `index represents labels`, `not positions`, and `labels can be numbers or strings`.**

- **If `no labels` are provided, `Pandas creates default numeric labels`, which may `look like list indexes but are still labels`.**

- **To `access data by position` in a `Pandas Series`, we must `use .iloc`, while `.loc is used for label-based access`.**

In [4]:
s = pd.Series([1, 2, 3, 4, 5]) 
print(s) 
print(type(s))

# access by labels not index
print(s[0])
print(s[2])
# printing index or labels
print(s.index)

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>
1
3
RangeIndex(start=0, stop=5, step=1)

In [5]:
s = pd.Series([100, 200, 300], index=["a", "b", "c"])
print(s)

"""Access using position (iloc)
Use this when you want Python-list-style access."""
print(s.iloc[0])   # first element
print(s.iloc[1])   # second element

"""Access using label explicitly (loc)
loc = label-based access"""
print(s.loc["a"])

a    100
b    200
c    300
dtype: int64
100
200
100

In [6]:
# custom labels
age = pd.Series([23, 24, 25, 26], index=["Adam", "Eve", "Bob", "Charlie"]) 
print(s)

#access by labels
print(age["Adam"])
# printing index or labels
print(age.index)

a    100
b    200
c    300
dtype: int64
23
Index(['Adam', 'Eve', 'Bob', 'Charlie'], dtype='str')

---

### **`` Pandas DataFrame``**

A DataFrame is a **two-dimensional, tabular data structure** (like a spreadsheet or 
SQL table). 

It consists of: 

- Rows 
- Columns 
- Index (row labels) 
- Column labels 

Each column in a DataFrame is a Series. 

`DataFrame` Properties:

- Hetrogenous (Each column is a Series → each Series can have its own dtype.)

- Column-wise homogeneous 

                    (DataFrame overall → heterogeneous

                        Individual columns → homogeneous)

- Vectorized operations (column-wise)

- Handle Missing values with NaN

- Mutable Values, mutable size (Internally, Pandas may create new objects, but conceptually DataFrames are mutable.)

In [7]:
# DataFrom using Dictionary of lists
info = {
    "Name" : ["Ali", "Sara", "Zoya"], 
    "Age" : [20, 21, 19], 
    "CGPA" : [3.5, 2.6, 3.1]
}

df = pd.DataFrame(info)

print(df)
print(type(df))

print(df.index) 
print(df.columns)

   Name  Age  CGPA
0   Ali   20   3.5
1  Sara   21   2.6
2  Zoya   19   3.1
<class 'pandas.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Age', 'CGPA'], dtype='str')

In [8]:
# column wise homogenous

print(df["Name"])   # all strings
print(df["Age"])

0     Ali
1    Sara
2    Zoya
Name: Name, dtype: str
0    20
1    21
2    19
Name: Age, dtype: int64

In [9]:
# Labeled rows AND labeled columns
print(df.index)
print(df.columns)

RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Age', 'CGPA'], dtype='str')

In [10]:
# size is mutable
df["Grade"] = ["A", "B", "A"]   # add column

print(df)

   Name  Age  CGPA Grade
0   Ali   20   3.5     A
1  Sara   21   2.6     B
2  Zoya   19   3.1     A

In [11]:
# supports Vectorized operations
add_age = df["Age"] + 5
print(add_age)

0    25
1    26
2    24
Name: Age, dtype: int64

In [12]:
df1 = pd.DataFrame({
    "Name" : ["Ali", "Sara", None], 
    "Age" : [20, None, 22]
})
# handling of missing values
"""Returns a DataFrame of True/False values:
True → value is missing
False → value is not missing"""
df1.isna()

    Name    Age
0  False  False
1  False   True
2   True  False

In [13]:
df1.isna().sum()

Name    1
Age     1
dtype: int64

In [14]:
"""It replaces missing values (NaN) with something you choose."""
# df1.fillna("missing")
df1.fillna(0)

   Name   Age
0   Ali  20.0
1  Sara   0.0
2     0  22.0

In [15]:
"""It removes rows that contain missing values."""
df1.dropna()

  Name   Age
0  Ali  20.0

In [16]:
# DataFrom using Lists
l = [["Adam", 96], ["Eve", 75], ["Bob", 82], ["Charlie", 92]]

df = pd.DataFrame(l, columns=["Name", "Marks"])
print(df)

      Name  Marks
0     Adam     96
1      Eve     75
2      Bob     82
3  Charlie     92

In [17]:
# DataFrom using Numpy array
import numpy as np

np_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

df = pd.DataFrame(np_arr, columns=["Col1", "Col2", "Col3"])
print(df)

   Col1  Col2  Col3
0     1     2     3
1     4     5     6
2     7     8     9