## **`Pandas with CSV and JSON data`**

- `CSV files` are read using `pd.read_csv()` and `JSON files` using `pd.read_json()`. 

- Pandas automatically converts them into DataFrames and provides options to `handle separators, headers, missing values, and nested JSON structures`.

---

In [13]:
import pandas as pd

### **1️⃣ — Working with CSV Files**

**`CSV = Comma Separated Values`**

In [15]:
df = pd.read_csv("employee_data.csv")
print(df, type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.DataFrame'>

### **2️⃣ — Working with JSON Data**

**`JSON = JavaScript Object Notation`**

In [3]:
df = pd.read_json("employee_data.json") 
print(df, type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.DataFrame'>

##  **🐼 Pandas DataFrame Methods**

#### 1️⃣ **`df.head()`**

- **Shows first 5 rows**

In [4]:
df.head()

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000

#### 2️⃣ **`df.tail()`**

- **Shows last 5 rows**

In [5]:
df.tail()

   ID    Name  Age Department  Salary
5   6   Frank   29    Finance   50000
6   7   Grace   41         HR   82000
7   8  Hannah   26  Marketing   47000
8   9     Ian   35         IT   75000
9  10   Julia   30    Finance   60000

In [6]:
df.tail(2)

   ID   Name  Age Department  Salary
8   9    Ian   35         IT   75000
9  10  Julia   30    Finance   60000

#### 3️⃣ **`df.shape`**

- **Returns (rows, columns)**
- **Extremely important for ML**

In [7]:
df.shape

(10, 5)

#### 4️⃣ **`df.info()`**

**Shows: column names, Data types, Non-null counts, Memory usage**

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     str
 2   Age         10 non-null     int64
 3   Department  10 non-null     str
 4   Salary      10 non-null     int64
dtypes: int64(3), str(2)
memory usage: 532.0 bytes

#### 5️⃣ **`df.describe()`**

- **Statistical summary:**
    **mean, std, min, max, quartiles**
    **Work for numeric columns**

In [9]:
df.describe()

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000

#### 6️⃣ **`df.sample()`**

- **Returns random rows**
- **Used to inspect data randomly**

In [10]:
df.sample()

   ID     Name  Age Department  Salary
2   3  Charlie   28    Finance   48000

#### 7️⃣ **`df.columns`**

- **Returns column names**
- **Very useful in cleaning**

In [11]:
df.columns

Index(['ID', 'Name', 'Age', 'Department', 'Salary'], dtype='str')

#### 8️⃣ **`df.nuinque()`**

- **Unique count**

In [12]:
df.nunique()

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64