## **`Pandas Filtering Data`**

- Filtering = selecting rows that satisfy a condition

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("globalAirQuality.csv") 

df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [3]:
df[(df["aqi"] > 100) & (df["temperature"] > 30)]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
6,2025-11-05 00:25:17.554219,US,New York,40.713,-74.006,77.690,65.198,20.302,7.641,62.687,0.734,155,36.729,47.651,4.542
7,2025-11-05 01:25:17.554219,US,New York,40.713,-74.006,57.816,111.709,34.533,6.945,41.304,0.771,115,37.891,53.314,7.605
14,2025-11-05 08:25:17.554219,US,New York,40.713,-74.006,38.815,121.394,25.969,4.112,44.730,1.124,121,34.481,81.790,3.576
17,2025-11-05 11:25:17.554219,US,New York,40.713,-74.006,63.552,57.838,13.754,4.427,42.251,0.997,127,36.193,62.906,7.097
25,2025-11-05 19:25:17.554219,US,New York,40.713,-74.006,56.954,75.045,29.837,9.541,54.198,1.170,113,31.289,43.279,5.264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17947,2025-11-17 13:25:17.554219,CH,Zurich,47.377,8.542,53.938,75.183,16.255,7.263,67.244,0.457,107,32.584,81.544,7.101
17950,2025-11-17 16:25:17.554219,CH,Zurich,47.377,8.542,70.255,60.620,32.081,2.065,47.803,0.852,140,36.885,34.173,1.748
17975,2025-11-18 17:25:17.554219,CH,Zurich,47.377,8.542,33.406,98.160,44.654,0.807,45.160,0.737,111,30.761,76.073,3.570
17976,2025-11-18 18:25:17.554219,CH,Zurich,47.377,8.542,73.493,89.558,9.313,4.768,51.505,0.745,146,30.909,81.573,1.024
17991,2025-11-19 09:25:17.554219,CH,Zurich,47.377,8.542,52.120,71.160,35.405,7.752,39.811,0.878,104,32.556,31.372,2.787

In [4]:
df[ df["aqi"] > 100] [["city", "aqi"]]

           city  aqi
0      New York  108
3      New York  158
6      New York  155
7      New York  115
8      New York  121
...         ...  ...
17991    Zurich  104
17993    Zurich  153
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122

[9721 rows x 2 columns]

| Filtering Type                 | Purpose                   | General Syntax                    | Example                                        |
| ------------------------------ | ------------------------- | --------------------------------- | ---------------------------------------------- |
| **Single condition**           | Filter by one rule        | `df[df["col"] op value]`          | `df[df["Age"] > 20]`                           |
| **AND condition**              | All conditions true       | `df[(cond1) & (cond2)]`           | `df[(df["Age"] > 20) & (df["Marks"] > 85)]`   |
| **OR condition**               | Any condition true        | `df[(cond1) \| (cond2)]`          | `df[(df["City"]=="Lahore") \| (df["City"]=="Karachi")]` |
| **NOT condition**              | Exclude values            | `df[~condition]`                  | `df[~(df["City"]=="Karachi")]`                 |
| **Select columns with filter** | Filter + column selection | `df.loc[condition, cols]`         | `df.loc[df["Marks"]>80, ["Name","Marks"]]`     |
| **Multiple values**            | Match from list           | `df[df["col"].isin(list)]`        | `df[df["City"].isin(["Lahore","Islamabad"])]`  |
| **String contains**            | Text filtering            | `df[df["col"].str.contains("x")]` | `df[df["Name"].str.contains("a", case=False)]` |
| **Starts / ends with**         | Prefix / suffix match     | `df["col"].str.startswith()`      | `df[df["Name"].str.startswith("A")]`           |
| **Missing values**             | NaN filtering             | `df["col"].isna()`                | `df[df["Age"].isna()]`                         |
| **Non-missing values**         | Valid data                | `df["col"].notna()`               | `df[df["Age"].notna()]`                        |
| **Query method**               | Clean readable filter     | `df.query("condition")`           | `df.query("Age > 20 and Marks > 85")`          |
| **Random sample**              | Random rows               | `df.sample(n)`                    | `df.sample(5)`                                 |

In [5]:
# single condition
df[df["aqi"] > 100]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
6,2025-11-05 00:25:17.554219,US,New York,40.713,-74.006,77.690,65.198,20.302,7.641,62.687,0.734,155,36.729,47.651,4.542
7,2025-11-05 01:25:17.554219,US,New York,40.713,-74.006,57.816,111.709,34.533,6.945,41.304,0.771,115,37.891,53.314,7.605
8,2025-11-05 02:25:17.554219,US,New York,40.713,-74.006,60.914,44.775,40.936,6.779,36.751,1.014,121,24.092,48.148,8.686
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17991,2025-11-19 09:25:17.554219,CH,Zurich,47.377,8.542,52.120,71.160,35.405,7.752,39.811,0.878,104,32.556,31.372,2.787
17993,2025-11-19 11:25:17.554219,CH,Zurich,47.377,8.542,76.613,37.495,29.662,5.419,57.042,1.103,153,20.437,79.602,2.663
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660

In [6]:
# AND condition
df[(df["aqi"] > 100) & (df["temperature"] > 30)]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
6,2025-11-05 00:25:17.554219,US,New York,40.713,-74.006,77.690,65.198,20.302,7.641,62.687,0.734,155,36.729,47.651,4.542
7,2025-11-05 01:25:17.554219,US,New York,40.713,-74.006,57.816,111.709,34.533,6.945,41.304,0.771,115,37.891,53.314,7.605
14,2025-11-05 08:25:17.554219,US,New York,40.713,-74.006,38.815,121.394,25.969,4.112,44.730,1.124,121,34.481,81.790,3.576
17,2025-11-05 11:25:17.554219,US,New York,40.713,-74.006,63.552,57.838,13.754,4.427,42.251,0.997,127,36.193,62.906,7.097
25,2025-11-05 19:25:17.554219,US,New York,40.713,-74.006,56.954,75.045,29.837,9.541,54.198,1.170,113,31.289,43.279,5.264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17947,2025-11-17 13:25:17.554219,CH,Zurich,47.377,8.542,53.938,75.183,16.255,7.263,67.244,0.457,107,32.584,81.544,7.101
17950,2025-11-17 16:25:17.554219,CH,Zurich,47.377,8.542,70.255,60.620,32.081,2.065,47.803,0.852,140,36.885,34.173,1.748
17975,2025-11-18 17:25:17.554219,CH,Zurich,47.377,8.542,33.406,98.160,44.654,0.807,45.160,0.737,111,30.761,76.073,3.570
17976,2025-11-18 18:25:17.554219,CH,Zurich,47.377,8.542,73.493,89.558,9.313,4.768,51.505,0.745,146,30.909,81.573,1.024
17991,2025-11-19 09:25:17.554219,CH,Zurich,47.377,8.542,52.120,71.160,35.405,7.752,39.811,0.878,104,32.556,31.372,2.787

In [11]:
# or condition
df[(df["city"]== "Taxila") | (df["temperature"] > 40)]

Empty DataFrame
Columns: [timestamp, country, city, latitude, longitude, pm25, pm10, no2, so2, o3, co, aqi, temperature, humidity, wind_speed]
Index: []

In [12]:
#not condition
df[~((df["country"]=="USA") & (df["city"]=="NewYork")) ]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [18]:
# Select columns with filters
df.loc[df["aqi"] > 200, ["country", "city", "temperature", "aqi"]]

      country      city  temperature  aqi
745        GB    London       19.055  214
8941       JP     Osaka       15.277  204
12956      NZ  Auckland       14.872  225
14555      PH    Manila       11.027  206
17458      FI  Helsinki       34.420  202
17529      FI  Helsinki       25.795  231
17815      CH    Zurich       20.883  203

## **`Filtering Data using query()`**

`query()` lets you filter rows using **SQL-like, English-style conditions** instead of boolean brackets.

General syntax: `df.query("condition")`

`query()` rules:

- Expression as a string
- Column based reference
- Backticks for col_name with space or special chars
- Operators (&, |, ~, >=, >, <=, <, == etc.)
- @ to reference Python vars
- chained comparison

In [20]:
df.query("aqi > 160")

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
81,2025-11-08 03:25:17.554219,US,New York,40.713,-74.006,83.676,83.653,33.346,2.594,83.375,0.598,167,19.683,37.565,1.764
112,2025-11-09 10:25:17.554219,US,New York,40.713,-74.006,96.012,102.666,38.339,6.486,42.027,1.643,192,32.786,32.631,6.679
189,2025-11-12 15:25:17.554219,US,New York,40.713,-74.006,84.020,82.172,27.977,2.662,26.646,0.534,168,21.036,60.274,3.584
194,2025-11-12 20:25:17.554219,US,New York,40.713,-74.006,49.974,51.775,71.926,5.630,38.331,0.383,179,22.125,44.262,4.973
197,2025-11-12 23:25:17.554219,US,New York,40.713,-74.006,46.633,58.539,65.824,6.580,51.101,0.995,164,19.835,85.392,5.577
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17821,2025-11-12 07:25:17.554219,CH,Zurich,47.377,8.542,83.401,57.483,30.061,2.951,43.426,0.619,166,35.425,78.880,2.702
17822,2025-11-12 08:25:17.554219,CH,Zurich,47.377,8.542,20.396,25.365,67.072,5.699,31.725,0.791,167,36.316,47.328,3.349
17885,2025-11-14 23:25:17.554219,CH,Zurich,47.377,8.542,52.162,35.304,76.076,6.090,44.849,0.557,190,6.196,32.675,4.792
17886,2025-11-15 00:25:17.554219,CH,Zurich,47.377,8.542,92.897,91.800,7.016,6.932,21.053,0.805,185,17.023,39.594,7.624
17888,2025-11-15 02:25:17.554219,CH,Zurich,47.377,8.542,51.223,69.873,64.933,6.655,31.039,1.017,162,8.356,82.557,3.340

In [22]:
df.query("aqi > 100 & temperature > 35") [["city", "aqi"]]

           city  aqi
6      New York  155
7      New York  115
17     New York  127
82     New York  122
105    New York  127
...         ...  ...
17866    Zurich  140
17874    Zurich  146
17883    Zurich  129
17902    Zurich  105
17950    Zurich  140

[909 rows x 2 columns]

In [23]:
aqi_value = 100
df.query("aqi > @aqi_value & temperature > 35") [["city", "aqi"]]

           city  aqi
6      New York  155
7      New York  115
17     New York  127
82     New York  122
105    New York  127
...         ...  ...
17866    Zurich  140
17874    Zurich  146
17883    Zurich  129
17902    Zurich  105
17950    Zurich  140

[909 rows x 2 columns]