## `Cleaning Data`

- ## **`Handling Missing Values 🐼`**

**In Pandas, missing data is usually represented as:**

- NaN (Not a Number)
- None
- NaT (for dates)

**Real-life reasons for missing data:**

- Data not collected
- Sensor failure
- User skipped a field
- Merging datasets

**Missing data is NORMAL, not an error.**

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("raw_data.csv") 
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

#### 1️⃣ **`isnull() / isna()`**

- Detecting missing values (ALWAYS first step)
- Returns True / False for every cell.

In [4]:
df.isnull()

       id   name    age  country  gender  income
0   False  False  False    False   False   False
1   False  False  False    False   False   False
2   False  False   True    False   False   False
3   False  False   True    False   False   False
4   False  False  False    False   False    True
5   False  False  False    False   False   False
6   False   True  False    False   False   False
7   False  False  False     True   False   False
8   False  False  False    False   False   False
9   False  False   True    False   False   False
10  False  False  False    False    True   False

In [5]:
df.isna()

       id   name    age  country  gender  income
0   False  False  False    False   False   False
1   False  False  False    False   False   False
2   False  False   True    False   False   False
3   False  False   True    False   False   False
4   False  False  False    False   False    True
5   False  False  False    False   False   False
6   False   True  False    False   False   False
7   False  False  False     True   False   False
8   False  False  False    False   False   False
9   False  False   True    False   False   False
10  False  False  False    False    True   False

#### 2️⃣ **`isnull().sum()`**

- Count missing values

In [6]:
df.isnull().sum()

id         0
name       1
age        3
country    1
gender     1
income     1
dtype: int64

#### 3️⃣ **`dropna()`**

- Removing missing values (Drop)

> ***Drop rows with ANY missing value***

In [7]:
df.dropna()

   id        name   age country  gender   income
0   1    John Doe  29.0     USA    Male  55000.0
1   1    John Doe  29.0     USA    Male  55000.0
5   5      Li Wei  27.0   China    Male  51000.0
8   8  Rachel Lee  29.0     USA  Female  62000.0

> ***Drop rows where ALL values are missing***

In [8]:
df.dropna(how="all")

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

> ***Drop rows based on specific columns***

In [9]:
df.dropna(subset=["age"])

    id          name   age country  gender   income
0    1      John Doe  29.0     USA    Male  55000.0
1    1      John Doe  29.0     USA    Male  55000.0
4    4  Maria Garcia  34.0   Spain  Female      NaN
5    5        Li Wei  27.0   China    Male  51000.0
6    6           NaN  45.0   India  Female  73000.0
7    7    Ahmed Khan  38.0     NaN    Male  68000.0
8    8    Rachel Lee  29.0     USA  Female  62000.0
10  10   Emily Davis  31.0     USA     NaN  58000.0

#### 4️⃣ **`fillna(value)`**

- Filling missing values

> ***Fill with a constant value***

In [10]:
df.fillna(0)
df.fillna("Unknown")

    id          name      age  country   gender   income
0    1      John Doe     29.0      USA     Male  55000.0
1    1      John Doe     29.0      USA     Male  55000.0
2    2    Jane Smith  Unknown   Canada   Female  62000.0
3    3          Alex  Unknown      USA  Unknown  47000.0
4    4  Maria Garcia     34.0    Spain   Female  Unknown
5    5        Li Wei     27.0    China     Male  51000.0
6    6       Unknown     45.0    India   Female  73000.0
7    7    Ahmed Khan     38.0  Unknown     Male  68000.0
8    8    Rachel Lee     29.0      USA   Female  62000.0
9    9   Carlos Ruiz  Unknown   Mexico     Male  45000.0
10  10   Emily Davis     31.0      USA  Unknown  58000.0

> ***Fill numeric columns with mean/ median***

In [11]:
cleaned_data = df.copy()
cleaned_data["age"] = cleaned_data["age"].fillna(df["age"].mean())

cleaned_data

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
1    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female      NaN
5    5        Li Wei  27.00   China     Male  51000.0
6    6           NaN  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     NaN     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA      NaN  58000.0

In [12]:
df["age"].fillna(df["age"].median)

0                                                  29.0
1                                                  29.0
2     <bound method Series.median of 0     29.0\n1  ...
3     <bound method Series.median of 0     29.0\n1  ...
4                                                  34.0
5                                                  27.0
6                                                  45.0
7                                                  38.0
8                                                  29.0
9     <bound method Series.median of 0     29.0\n1  ...
10                                                 31.0
Name: age, dtype: object

> ***Fill categorical data with mode***

In [13]:
df["country"].fillna(df["country"].mode()[0])

0        USA
1        USA
2     Canada
3        USA
4      Spain
5      China
6      India
7        USA
8        USA
9     Mexico
10       USA
Name: country, dtype: str

#### 5️⃣ **`ffill()`**

- Forward fill (time-based data)

In [14]:
df.ffill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  29.0  Canada   Female  62000.0
3    3          Alex  29.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  47000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6        Li Wei  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0   India     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  29.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA     Male  58000.0

#### 6️⃣ **`bfill()`**

- backward fill (time-based data)

In [15]:
df.bfill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

#### 7️⃣ **`Filling multiple columns differently`**

In [16]:
df.fillna({
    "country" : df["country"].ffill(),
    "age" : df["age"].mean(),
    "gender" : "NA"
})

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
1    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female      NaN
5    5        Li Wei  27.00   China     Male  51000.0
6    6           NaN  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00   India     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA       NA  58000.0

#### 8️⃣ **`In-place vs not`**

**What inplace=True actually does**

- Many Pandas methods (like fillna, drop, sort_values) can either:

   - Return a new DataFrame with changes applied.

   - Modify the original DataFrame directly.

`inplace=True` means:

"Do the operation **directly on the existing DataFrame**, instead of creating a copy."

- Avoid `inplace=True` in ML pipelines — assign back instead.

In [17]:
# Fill numeric columns with a number
# df['age'].fillna(0, inplace=True)
# df['income'].fillna(0, inplace=True)

# # Fill object/string columns with "None"
# df['name'].fillna("None", inplace=True)
# df['country'].fillna("None", inplace=True)
# df['gender'].fillna("None", inplace=True)

- ## **`Handling Duplicate Values 🐼`**

- **Duplicate data = repeated rows or repeated values that should logically appear only once**

- Duplicates silently break analysis & ML models

| Task             | Code                                 |
| ---------------- | ------------------------------------ |
| Check duplicates | `df.duplicated()`                    |
| Count duplicates | `df.duplicated().sum()`              |
| View duplicates  | `df[df.duplicated()]`                |
| Drop duplicates  | `df.drop_duplicates()`               |
| Based on column  | `df.drop_duplicates(subset=["col"])` |
| Keep last        | `keep="last"`                        |
| Drop all         | `keep=False`                         |

#### 1️⃣ **`duplicated()`**

In [18]:
# check duplicates
df.duplicated()

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

In [19]:
# count duplicates
df.duplicated().sum()

np.int64(1)

In [20]:
# view duplicates
df[df.duplicated()]

   id      name   age country gender   income
1   1  John Doe  29.0     USA   Male  55000.0

In [21]:
# column wise
df[["country", "gender"]].duplicated()

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

#### 2️⃣ **`drop_duplicates`**

In [22]:
# drop duplicates
df2 = df.copy()

df2.drop_duplicates(inplace=True)
df2

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [23]:
# based on column
df.drop_duplicates(subset=["name"])

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

- ## **`Handling Data Types & data-time 🐼`**

- If data types are wrong:

  - Math fails

  - Sorting breaks

  - ML models reject data

- 80% bugs in ML pipelines come from wrong data types

####  **Common Wrong Data Type Problems**  |  **Golden Data Type Cleaning Strategy**


| Problem | Example | Correct Data Type | Best Method |
|----------|----------|------------------|-------------|
| Numbers stored as text | `"45"`, `"1000"` | Numeric | `pd.to_numeric()` |
| Dates stored as strings | `"2024-01-15"` | `datetime` | `pd.to_datetime()` |
| Mixed types in column | `10`, `"unknown"` | Numeric (cleaned) | `pd.to_numeric(errors="coerce")` |
| Boolean stored as text | `"yes"`, `"no"` | Boolean | `.map({"yes": True, "no": False})` |
| Repeated text categories | `"Male"`, `"Female"` | `category` | `.astype("category")` |

In [24]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

#### 1️⃣ **`dtypes`**

In [25]:
df.dtypes

id           int64
name           str
age        float64
country        str
gender         str
income     float64
dtype: object

In [26]:
df["age"].astype("Int64")

0       29
1       29
2     <NA>
3     <NA>
4       34
5       27
6       45
7       38
8       29
9     <NA>
10      31
Name: age, dtype: Int64

In [27]:
# converting with error handling
df["income"] = pd.to_numeric(df["income"], errors="coerce")
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

#### 2️⃣ **`astype(newtype)`**

In [28]:
df2 = df.copy() 
df2 = df2.fillna(0)
df2["age"] = df2["age"].astype("int64") 
df2

    id          name  age country   gender   income
0    1      John Doe   29     USA     Male  55000.0
1    1      John Doe   29     USA     Male  55000.0
2    2    Jane Smith    0  Canada   Female  62000.0
3    3          Alex    0     USA  Unknown  47000.0
4    4  Maria Garcia   34   Spain   Female      0.0
5    5        Li Wei   27   China     Male  51000.0
6    6             0   45   India   Female  73000.0
7    7    Ahmed Khan   38       0     Male  68000.0
8    8    Rachel Lee   29     USA   Female  62000.0
9    9   Carlos Ruiz    0  Mexico     Male  45000.0
10  10   Emily Davis   31     USA        0  58000.0

#### 3️⃣ **`to_datetime()`**

Pandas auto-detects:

- Formats

- Time

- Timezone (sometimes)

In [29]:
date_string = pd.Series([pd.to_datetime("2026-12-31") ])
type(date_string.dtypes)

numpy.dtypes.DateTime64DType

In [30]:
aqi_data = pd.read_csv("globalAirQuality.csv") 
aqi_data

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [31]:
aqi_data["timestamp"].dtype

In [32]:
copy_data = aqi_data.copy()
copy_data["timestamp"] = pd.to_datetime(copy_data["timestamp"], errors="coerce")
copy_data

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [33]:
copy_data["timestamp"].dtype

dtype('<M8[us]')

In [34]:
copy_data["Year"] = copy_data["timestamp"].dt.year 
copy_data["Month"] = copy_data["timestamp"].dt.month 
copy_data["Day"] = copy_data["timestamp"].dt.day
copy_data["Weekday"] = copy_data["timestamp"].dt.day_name()

In [35]:
copy_data.sort_values("timestamp")

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed,Year,Month,Day,Weekday
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725,2025,11,4,Tuesday
7200,2025-11-04 18:25:17.554219,IN,Bengaluru,12.972,77.595,5.001,54.210,16.889,6.382,48.177,0.712,54,16.939,86.850,4.244,2025,11,4,Tuesday
6840,2025-11-04 18:25:17.554219,IN,Delhi,28.704,77.102,44.829,28.334,9.180,6.874,49.548,0.911,89,33.540,40.150,7.473,2025,11,4,Tuesday
16920,2025-11-04 18:25:17.554219,SE,Stockholm,59.329,18.069,46.500,33.297,52.367,7.162,54.054,0.386,130,19.640,51.401,9.353,2025,11,4,Tuesday
6480,2025-11-04 18:25:17.554219,IN,Mumbai,19.076,72.878,45.820,86.378,19.605,7.877,42.399,0.432,91,10.045,89.524,9.220,2025,11,4,Tuesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10439,2025-11-19 17:25:17.554219,HK,Hong Kong,22.319,114.169,26.114,83.559,25.910,5.039,60.426,0.665,83,36.834,44.699,4.339,2025,11,19,Wednesday
10079,2025-11-19 17:25:17.554219,CN,Shanghai,31.230,121.474,60.845,38.593,44.208,5.921,63.010,0.215,121,6.785,58.257,8.940,2025,11,19,Wednesday
9719,2025-11-19 17:25:17.554219,CN,Beijing,39.904,116.407,38.677,100.093,19.818,10.400,42.899,1.178,100,25.617,59.467,4.836,2025,11,19,Wednesday
8639,2025-11-19 17:25:17.554219,JP,Tokyo,35.676,139.650,20.839,81.735,40.879,9.259,57.167,0.922,102,14.800,33.239,8.711,2025,11,19,Wednesday
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403,2025,11,19,Wednesday

In [36]:
# time based filtering
copy_data[copy_data["timestamp"] > "2025-11-19"]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed,Year,Month,Day,Weekday
342,2025-11-19 00:25:17.554219,US,New York,40.713,-74.006,58.895,56.328,44.016,5.410,24.319,0.584,117,9.818,78.627,1.276,2025,11,19,Wednesday
343,2025-11-19 01:25:17.554219,US,New York,40.713,-74.006,60.870,55.081,1.281,6.839,62.873,0.550,121,28.786,56.263,8.077,2025,11,19,Wednesday
344,2025-11-19 02:25:17.554219,US,New York,40.713,-74.006,29.917,71.468,46.932,7.892,36.590,0.655,117,12.635,37.549,1.798,2025,11,19,Wednesday
345,2025-11-19 03:25:17.554219,US,New York,40.713,-74.006,35.776,86.283,15.967,6.314,29.400,0.758,86,29.129,71.951,7.232,2025,11,19,Wednesday
346,2025-11-19 04:25:17.554219,US,New York,40.713,-74.006,22.025,63.197,22.625,5.188,60.293,1.111,63,9.723,79.409,9.241,2025,11,19,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452,2025,11,19,Wednesday
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496,2025,11,19,Wednesday
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660,2025,11,19,Wednesday
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642,2025,11,19,Wednesday
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403,2025,11,19,Wednesday

- ## **`Handling Strings 🐼`**

- **In Pandas:**

  **String operations are vectorized using .str**

In [37]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

#### **1. Case Conversion**
| Method              | What it does         | Example                     |
| ------------------- | -------------------- | --------------------------- |
| `.str.lower()`      | Convert to lowercase | `"Ali"` → `"ali"`           |
| `.str.upper()`      | Convert to uppercase | `"Ali"` → `"ALI"`           |
| `.str.title()`      | Title case           | `"john doe"` → `"John Doe"` |
| `.str.capitalize()` | First letter capital | `"ali"` → `"Ali"`           |
| `.str.swapcase()`   | Swap upper/lower     | `"Ali"` → `"aLI"`           |

In [38]:
df["gender"].str.capitalize()

0        Male
1        Male
2      Female
3     Unknown
4      Female
5        Male
6      Female
7        Male
8      Female
9        Male
10        NaN
Name: gender, dtype: str

#### **2. Removing & Trimming Spaces**
| Method          | What it does               | Example             |
| --------------- | -------------------------- | ------------------- |
| `.str.strip()`  | Remove spaces (both sides) | `" Ali "` → `"Ali"` |
| `.str.lstrip()` | Remove left spaces         | `" Ali"` → `"Ali"`  |
| `.str.rstrip()` | Remove right spaces        | `"Ali "` → `"Ali"`  |

In [39]:
df["name"].str.strip()

0         John Doe
1         John Doe
2       Jane Smith
3             Alex
4     Maria Garcia
5           Li Wei
6              NaN
7       Ahmed Khan
8       Rachel Lee
9      Carlos Ruiz
10     Emily Davis
Name: name, dtype: str

#### **3. Replace & Clean Text**
| Method                | What it does  | Example               |
| --------------------- | ------------- | --------------------- |
| `.str.replace(a, b)`  | Replace text  | `"Karachi"` → `"KHI"` |
| `.str.replace(regex)` | Regex replace | Remove extra spaces   |

In [40]:
df["country"].str.replace("USA", "Pakistan")

0     Pakistan
1     Pakistan
2       Canada
3     Pakistan
4        Spain
5        China
6        India
7          NaN
8     Pakistan
9       Mexico
10    Pakistan
Name: country, dtype: str

#### **4. Searching & Matching (Filtering Helper)**
| Method              | Use case         | Returns |
| ------------------- | ---------------- | ------- |
| `.str.contains()`   | Check substring  | Boolean |
| `.str.startswith()` | Starts with text | Boolean |
| `.str.endswith()`   | Ends with text   | Boolean |
| `.str.match()`      | Full regex match | Boolean |
| `.str.findall()`    | Find all matches | List    |

In [41]:
df["country"].str.contains("india", case=False)

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7     False
8     False
9     False
10    False
Name: country, dtype: bool

#### **5. Splitting & Combining Strings**
| Method             | What it does        | Example               |
| ------------------ | ------------------- | --------------------- |
| `.str.split()`     | Split text          | `"A B"` → `["A","B"]` |
| `.str.rsplit()`    | Split from right    |                       |
| `.str.partition()` | Split into 3 parts  |                       |
| `.str.join()`      | Join characters     | `"abc"` → `"a-b-c"`   |
| `.str.cat()`       | Concatenate columns | Combine names         |

In [42]:
df["name"].str.split(" ")

0         [John, Doe]
1         [John, Doe]
2       [Jane, Smith]
3              [Alex]
4     [Maria, Garcia]
5           [Li, Wei]
6                 NaN
7       [Ahmed, Khan]
8       [Rachel, Lee]
9      [Carlos, Ruiz]
10     [Emily, Davis]
Name: name, dtype: object

#### **6. Extracting Data (Regex Power)**
| Method              | What it extracts  | Example         |
| ------------------- | ----------------- | --------------- |
| `.str.extract()`    | First regex group | Email domain    |
| `.str.extractall()` | All regex matches | Multiple values |

In [43]:
# df["Domain"] = df["Email"].str.extract(r"@(.+)")

#### **7. Length & Counting**
| Method         | What it gives    |
| -------------- | ---------------- |
| `.str.len()`   | Length of string |
| `.str.count()` | Count pattern    |

In [44]:
df["name"].str.len()

0      8.0
1      8.0
2     10.0
3      4.0
4     12.0
5      6.0
6      NaN
7     10.0
8     10.0
9     11.0
10    11.0
Name: name, dtype: float64

#### **8. Encoding, Padding & Formatting (Less common)**
| Method          | Use case          |
| --------------- | ----------------- |
| `.str.pad()`    | Pad strings       |
| `.str.zfill()`  | Zero fill numbers |
| `.str.center()` | Center align      |
| `.str.ljust()`  | Left align        |
| `.str.rjust()`  | Right align       |

#### **9. Character Validation (Checks)**
| Method             | Checks if string is |
| ------------------ | ------------------- |
| `.str.isalpha()`   | Alphabet only       |
| `.str.isnumeric()` | Numeric             |
| `.str.isdigit()`   | Digits              |
| `.str.isalnum()`   | Alpha + numeric     |
| `.str.isspace()`   | Only spaces         |
| `.str.islower()`   | Lowercase           |
| `.str.isupper()`   | Uppercase           |
| `.str.istitle()`   | Title case          |

#### **10. Useful Utility Methods**
| Method                 | Purpose              |
| ---------------------- | -------------------- |
| `.str.slice()`         | Slice strings        |
| `.str.slice_replace()` | Replace slice        |
| `.str.normalize()`     | Unicode normalize    |
| `.str.get()`           | Get element by index |