## **`Pandas Data Transformation`**

**What is Data Transformation?**

Changing data into a **better, usable form**.

Examples:

- Creating new columns
- Changing values
- Scaling or mapping values
- Applying functions to columns

### **`Applying Functions `**
| Method      | What it does                   | Intuition                |
| ----------- | ------------------------------ | ------------------------ |
| `apply()`   | Apply a function to a Series or DataFrame. | “Do this to every value” |
| `map()`     | Map a function or dictionary to a Series.   | “Translate values”       |
| `replace()` | Replace specific values in a series or DataFrame.       | “Find & replace”         |
| `assign()`  | Create new columns or modify existing columns.          | “Add smart columns”      |

In [73]:
import pandas as pd

In [74]:
df = pd.read_csv("raw_data.csv") 
df2 = df.copy()  # making copy of original data
df2

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [75]:
# creating a tax column 
df2["tax"] = df2["income"].apply(lambda x: "20%" if x >= 60000 else "10%")  # high order function (apply) : if a function takes another function as a parameter
df2

    id          name   age country   gender   income  tax
0    1      John Doe  29.0     USA     Male  55000.0  10%
1    1      John Doe  29.0     USA     Male  55000.0  10%
2    2    Jane Smith   NaN  Canada   Female  62000.0  20%
3    3          Alex   NaN     USA  Unknown  47000.0  10%
4    4  Maria Garcia  34.0   Spain   Female      NaN  10%
5    5        Li Wei  27.0   China     Male  51000.0  10%
6    6           NaN  45.0   India   Female  73000.0  20%
7    7    Ahmed Khan  38.0     NaN     Male  68000.0  20%
8    8    Rachel Lee  29.0     USA   Female  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0  10%
10  10   Emily Davis  31.0     USA      NaN  58000.0  10%

In [76]:
# maping 
gender_map = {"Male" : "M", "Female" : "F", "Unknown" : "U"} 
df2["gender"] = df2["gender"].map(gender_map) 
df2

    id          name   age country gender   income  tax
0    1      John Doe  29.0     USA      M  55000.0  10%
1    1      John Doe  29.0     USA      M  55000.0  10%
2    2    Jane Smith   NaN  Canada      F  62000.0  20%
3    3          Alex   NaN     USA      U  47000.0  10%
4    4  Maria Garcia  34.0   Spain      F      NaN  10%
5    5        Li Wei  27.0   China      M  51000.0  10%
6    6           NaN  45.0   India      F  73000.0  20%
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%
8    8    Rachel Lee  29.0     USA      F  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%
10  10   Emily Davis  31.0     USA    NaN  58000.0  10%

In [77]:
# creating new column
df2 = df2.assign(new_income = df2["income"] * 1.1)

In [78]:
# replacing specific values
df2["country"] = df["country"].replace("USA", "US") 
df2

    id          name   age country gender   income  tax  new_income
0    1      John Doe  29.0      US      M  55000.0  10%     60500.0
1    1      John Doe  29.0      US      M  55000.0  10%     60500.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN      US      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0   China      M  51000.0  10%     56100.0
6    6           NaN  45.0   India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0      US    NaN  58000.0  10%     63800.0

### **`Transformation Methods (Structure + Order)`**
| Method          | What it does            | Why we use it              | Intuition           |
| --------------- | ----------------------- | -------------------------- | ------------------- |
| `rename()`      | Rename columns or index | Improve clarity, fix names | “Give better names” |
| `sort_values()` | Sort values in ascending or descending order.    | Ranking, trends            | “Order by value”    |
| `sort_index()`  |  Sort indexes in ascending or descending order.           | Clean indexing             | “Order by index”    |
| `reset_index()` | Reset index to 0,1,2…   | After filtering/groupby    | “Clean the index”   |
| `rank()`        | Sort values in ascending or descending order,             resolves the ties.   | Competition, scoring       | “Who’s 1st, 2nd?”   |
| Reorder columns | Change column sequence  | Readability, reporting     | “Arrange layout”    |

In [79]:
df2.columns = ["Id", "Name", "Age", "Country", "Gender", "Income", "Tax", "New_Income"]
df2 = df2.rename(columns={"Income":"Salary"}) 
# df2.rename(index={1: "First"})

In [80]:
sorted_df2 = df2.sort_values("Salary", ascending=False)
sorted_df2

    Id          Name   Age Country Gender   Salary  Tax  New_Income
6    6           NaN  45.0   India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
10  10   Emily Davis  31.0      US    NaN  58000.0  10%     63800.0
0    1      John Doe  29.0      US      M  55000.0  10%     60500.0
1    1      John Doe  29.0      US      M  55000.0  10%     60500.0
5    5        Li Wei  27.0   China      M  51000.0  10%     56100.0
3    3          Alex   NaN      US      U  47000.0  10%     51700.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN

In [81]:
sorted_df2.sort_index()

    Id          Name   Age Country Gender   Salary  Tax  New_Income
0    1      John Doe  29.0      US      M  55000.0  10%     60500.0
1    1      John Doe  29.0      US      M  55000.0  10%     60500.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN      US      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0   China      M  51000.0  10%     56100.0
6    6           NaN  45.0   India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0      US    NaN  58000.0  10%     63800.0

In [82]:
sorted_df2

    Id          Name   Age Country Gender   Salary  Tax  New_Income
6    6           NaN  45.0   India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
10  10   Emily Davis  31.0      US    NaN  58000.0  10%     63800.0
0    1      John Doe  29.0      US      M  55000.0  10%     60500.0
1    1      John Doe  29.0      US      M  55000.0  10%     60500.0
5    5        Li Wei  27.0   China      M  51000.0  10%     56100.0
3    3          Alex   NaN      US      U  47000.0  10%     51700.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN

In [83]:
sorted_df2.reset_index()

    index  Id          Name   Age Country Gender   Salary  Tax  New_Income
0       6   6           NaN  45.0   India      F  73000.0  20%     80300.0
1       7   7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
2       8   8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0
3       2   2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
4      10  10   Emily Davis  31.0      US    NaN  58000.0  10%     63800.0
5       0   1      John Doe  29.0      US      M  55000.0  10%     60500.0
6       1   1      John Doe  29.0      US      M  55000.0  10%     60500.0
7       5   5        Li Wei  27.0   China      M  51000.0  10%     56100.0
8       3   3          Alex   NaN      US      U  47000.0  10%     51700.0
9       9   9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
10      4   4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN

In [84]:
sorted_df2["Ranking"] = sorted_df2["Salary"].rank(ascending=False, method="dense")
sorted_df2

    Id          Name   Age Country Gender   Salary  Tax  New_Income  Ranking
6    6           NaN  45.0   India      F  73000.0  20%     80300.0      1.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0      2.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0      3.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0      3.0
10  10   Emily Davis  31.0      US    NaN  58000.0  10%     63800.0      4.0
0    1      John Doe  29.0      US      M  55000.0  10%     60500.0      5.0
1    1      John Doe  29.0      US      M  55000.0  10%     60500.0      5.0
5    5        Li Wei  27.0   China      M  51000.0  10%     56100.0      6.0
3    3          Alex   NaN      US      U  47000.0  10%     51700.0      7.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0      8.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN      NaN

In [85]:
sorted_df2[["Id", "Name", "Age", "Country", "Gender", "Salary", "New_Income", "Tax"]]

    Id          Name   Age Country Gender   Salary  New_Income  Tax
6    6           NaN  45.0   India      F  73000.0     80300.0  20%
7    7    Ahmed Khan  38.0     NaN      M  68000.0     74800.0  20%
8    8    Rachel Lee  29.0      US      F  62000.0     68200.0  20%
2    2    Jane Smith   NaN  Canada      F  62000.0     68200.0  20%
10  10   Emily Davis  31.0      US    NaN  58000.0     63800.0  10%
0    1      John Doe  29.0      US      M  55000.0     60500.0  10%
1    1      John Doe  29.0      US      M  55000.0     60500.0  10%
5    5        Li Wei  27.0   China      M  51000.0     56100.0  10%
3    3          Alex   NaN      US      U  47000.0     51700.0  10%
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0     49500.0  10%
4    4  Maria Garcia  34.0   Spain      F      NaN         NaN  10%

In [86]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [89]:
df_copy = df.copy()

new_col_order = [col for col in df_copy.columns if col != "id"] + ["id"]

df_copy[new_col_order]

            name   age country   gender   income  id
0       John Doe  29.0     USA     Male  55000.0   1
1       John Doe  29.0     USA     Male  55000.0   1
2     Jane Smith   NaN  Canada   Female  62000.0   2
3           Alex   NaN     USA  Unknown  47000.0   3
4   Maria Garcia  34.0   Spain   Female      NaN   4
5         Li Wei  27.0   China     Male  51000.0   5
6            NaN  45.0   India   Female  73000.0   6
7     Ahmed Khan  38.0     NaN     Male  68000.0   7
8     Rachel Lee  29.0     USA   Female  62000.0   8
9    Carlos Ruiz   NaN  Mexico     Male  45000.0   9
10   Emily Davis  31.0     USA      NaN  58000.0  10