## **`GroupBy & Aggregation in Pandas`**

**Grouping means splitting data into groups based on one or more columns.**

Example groups:
   - Department-wise
   - City-wise
   - Category-wise
   
> **We use the `groupby` method to split data into multiple groups so that we can apply some aggregation functions on it.**

**Aggregation means summarizing each group using functions.**

Common summaries:
   - Mean
   - Sum
   - Count
   - Max / Min

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    'Department' : ["IT", "IT", "HR", "HR", "Sales"],
    "Employee" : ["A", "B", "C", "D", "E"], 
    "Salary" : [60_000, 65_000, 50_000, 52_000, 70_000]
})
df

  Department Employee  Salary
0         IT        A   60000
1         IT        B   65000
2         HR        C   50000
3         HR        D   52000
4      Sales        E   70000

In [6]:
df.groupby("Department")["Salary"].mean()
df.groupby("Department")["Salary"].min()
df.groupby("Department")["Salary"].max()

Department
HR       52000
IT       65000
Sales    70000
Name: Salary, dtype: int64

In [8]:
df.groupby("Department")["Salary"].agg(["mean", "min", "max"])
df.groupby("Department")["Salary"].aggregate(["mean", "min", "max"])

               mean    min    max
Department
HR          51000.0  50000  52000
IT          62500.0  60000  65000
Sales       70000.0  70000  70000

In [9]:
df.groupby("Department")["Salary"].agg(avg_salay="mean", min_salary="min", max_salary="max")

            avg_salay  min_salary  max_salary
Department
HR            51000.0       50000       52000
IT            62500.0       60000       65000
Sales         70000.0       70000       70000

In [10]:
df.groupby(['Department', 'Employee'])['Salary'].sum()

Department  Employee
HR          C           50000
            D           52000
IT          A           60000
            B           65000
Sales       E           70000
Name: Salary, dtype: int64

In [11]:
df.groupby("Department").agg({
    "Salary" : ["mean", "max"], 
    "Employee" : "count"
})

             Salary        Employee
               mean    max    count
Department
HR          51000.0  52000        2
IT          62500.0  65000        2
Sales       70000.0  70000        1

In [12]:
df.groupby('Department').agg(
    avg_salary=('Salary', 'mean'),
    max_salary=('Salary', 'max'),
    emp_count=('Employee', 'count')
)

            avg_salary  max_salary  emp_count
Department
HR             51000.0       52000          2
IT             62500.0       65000          2
Sales          70000.0       70000          1