## **`Reshaping Data in Pandas: melt() & pivot()`**

>**Same data, different shape → different insight**

Sometimes our data is:

 - Good for humans to read
 - Bad for analysis or plotting

So we reshape it.

`Wide → many columns`
`Long → fewer columns, more rows`

---

In [19]:
import pandas as pd

### **1️⃣ `melt()` — Wide ➜ Long**

`melt()` **turns columns into rows**

**Why do we need melt()?**

- Visualization (Seaborn loves long data)
- EDA
- Feature engineering
- Standardized datasets

In [20]:
"""syntax: 

pd.melt(
    df,
    id_vars= [fixed_columns],
    value_vars= [columns_to_melt],
    var_name= new_column_name,
    value_name= new_value_name
)
"""
df = pd.DataFrame({
    "Month" : ["Jan", "Feb", "Mar"], 
    "Product_A" : [120, 150, 170],
    "Product_B" : [90, 110, 130],
    "Product_C" : [60, 80, 100]
})

df

  Month  Product_A  Product_B  Product_C
0   Jan        120         90         60
1   Feb        150        110         80
2   Mar        170        130        100

In [21]:
melted_data = df.melt(
    id_vars=["Month"],
    value_vars=["Product_A", "Product_B", "Product_C"],
    var_name="Product_Categ",
    value_name="Sales"
)

melted_data

  Month Product_Categ  Sales
0   Jan     Product_A    120
1   Feb     Product_A    150
2   Mar     Product_A    170
3   Jan     Product_B     90
4   Feb     Product_B    110
5   Mar     Product_B    130
6   Jan     Product_C     60
7   Feb     Product_C     80
8   Mar     Product_C    100

---

### **2️⃣ `pivot()` — Long ➜ Wide**

`pivot()` **turns rows into columns.**

**Why do we need pivot()?**

- Reports & dashboards
- Feature matrix for ML
- Readable tables

> Important Rule of pivot():  Index + columns combination must be unique

In [22]:
"""Syntax:
df.pivot(
    index='row_identifier',
    columns='column_identifier',
    values='cell_values'
)
"""

melted_data

  Month Product_Categ  Sales
0   Jan     Product_A    120
1   Feb     Product_A    150
2   Mar     Product_A    170
3   Jan     Product_B     90
4   Feb     Product_B    110
5   Mar     Product_B    130
6   Jan     Product_C     60
7   Feb     Product_C     80
8   Mar     Product_C    100

In [24]:
# converting melted_data to original
pivot_data = melted_data.pivot(
    index="Month",
    columns="Product_Categ",
    values="Sales"
)
pivot_data

Product_Categ  Product_A  Product_B  Product_C
Month
Feb                  150        110         80
Jan                  120         90         60
Mar                  170        130        100

---

### **2️⃣ `pivot_table()`**

`pivot_table()` is used to **summarize and reshape data** when **duplicate values exist.**

> It is like `pivot() + groupby() + aggregation` in one step.

**Why do we need pivot_table()?**

- `pivot()` fails when there are **duplicate combinations**
- Real-world data often has:
    - Multiple transactions
    - Repeated records

- `pivot_table()` **solves this by aggregating duplicates**

> Industry data → pivot_table() is safer than pivot()

In [25]:
"""Syntax:
pd.pivot_table(
    data,
    index=...,     # rows
    columns=...,   # columns
    values=...,    # numbers to summarize
    aggfunc=...    # how to combine duplicates
)
"""
data = pd.DataFrame({
    "Month" : ["Jan", "Jan", "Jan", "Feb", "Feb"],
    "Product" : ["A", "A", "B", "A", "B"], 
    "Sales" : [120, 130, 90, 150, 110]
})

data

  Month Product  Sales
0   Jan       A    120
1   Jan       A    130
2   Jan       B     90
3   Feb       A    150
4   Feb       B    110

In [27]:
data_table = data.pivot_table(
    index="Month",
    columns="Product",
    values="Sales",
    aggfunc=["mean", "sum", "count", "max", "min"]
)

data_table

          mean         sum      count     max       min
Product      A      B    A    B     A  B    A    B    A    B
Month
Feb      150.0  110.0  150  110     1  1  150  110  150  110
Jan      125.0   90.0  250   90     2  1  130   90  120   90